import numpy as np
init = np.loadtxt("cell_vertices_initial.txt")
print(init.shape)
centroid = np.array([77.30223623, 77.03447408, 66.74390624])
lamda = .9
x = np.array((init[:,0]-centroid[0])*1/lamda**.5+centroid[0])
y = np.array((init[:,1]-centroid[1])*1/lamda**.5+centroid[1])
z = np.array((init[:,2]-centroid[2])*lamda+centroid[2])
# x = np.array((init[:,0]-.1))
# y = np.array((init[:,1]-.1))
# z = np.array((init[:,2]-.1))
stretch = np.column_stack([x,y,z])
# print(stretch[:,1])
# print(init[:][0]-centroid[0])
print(stretch.shape)
# print(np.array((init[:][0]-centroid[0])*1/lamda**1/2))
print(init[0])
print(stretch[0])
# stretch = np.array([(init[:,0]-centroid[0])*1/lamda**1/2,(init[:,0]-centroid[0])*1/lamda**1/2,(init[:,0]-centroid[0])*lamda]).swapaxes(0,1)
np.save("cell_vertices_stretched.npy",stretch)
